### ISSUE TITLE
Добавьте out в .gitignore

### ISSUE THREAD

**Issue by vitaly-chibrikov** [akukushkin/tp_2015_02_game21#1]
Не стоит в систему контроля версий добавлять бинарники

**Comment by akukushkin** [comment]
Хорошо, добавим

четверг, 5 марта 2015 г. пользователь Vitaly написал:

**Comment by vitaly-chibrikov** [comment]
С другой стороны, если вы храните версии server.jar для работы над фронтендом, то лучше заведите директорию serverbin и храните в ней. Но не как сейчас в корне и в out

**Comment by akukushkin** [comment]
Тогда grun'у указать, чтобы он искал jar'ник в serverbin?
